### ISSUE TITLE
Colocar dados do TREPB no storage.

### ISSUE THREAD

**Issue by danielfireman** [dadosjusbr/coletores#11]
Criar programa que executar o coletor baseado em um string de entrada, mês e ano e executa um método que realiza a coleta para depois armazenar no storage.

Essa issue diz respeito apenas para o trepb, mas a ideia é a gente usar esse programinha para popular os dados dos demais tribunais. Essa issue depende de https://github.com/dadosjusbr/storage/issues/4

**Comment by marcosbmf** [comment]
#16 resolve o problema.
