### ISSUE TITLE
Aspas indesejadas nas strings dos csvs

### ISSUE THREAD

**Issue by nazareno** [dadosjusbr/coletores#113]
Ao menos no MPPB, e nos dados dos meses 1 e 6 de 2020. Exemplo de uma linha dos dados: 

`"""mppb"""," 2020"," 1","""508276"""," ""ADEMAR LOPES NETO"""," ""PROMOTOR DE JUSTICA DE 1ª ENTRÂNCIA - APOSENTADO(A) """," ""membro"""," ""PBPREV"""," false",33689.11,33689.11,0.00,0.00,,,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,,,,0.00,9863.14,3034.68,0.00,6828.46,0.00
`
Há aspas extra em totdas as strings.

Fiquei na dúvida, mas parece que há também um espaço no 2020, e tinha a impressão que o ano e o mês deveriam ser números, e não strings.

**Comment by joeberth** [comment]
Realmente os arquivos que estão em produção, possuem essas falhas. 
Terminamos de deixar o Alba funcional, um dos próximos passos é estabelecer novas structs e executar a recoleta dos dados, esses problemas já estão sanados localmente, iremos atualizar esses dados em breve.

![image](https://user-images.githubusercontent.com/33490097/99024709-e206ce00-2545-11eb-8dd6-40eeca0433d4.png)
