### ISSUE TITLE
Erro de execução TRT13

### ISSUE THREAD

**Issue by joeberth** [dadosjusbr/coletores#142]
![WhatsApp Image 2020-11-09 at 17 32 03 (1)](https://user-images.githubusercontent.com/33490097/98611982-e88d0f80-22d1-11eb-9228-b56fbe13d0ca.jpeg)

Esse tipo de erro vem da saída de erro padrão, além disso a execução deveria parar quando existir algo no stderr, o que nao ocorre.

**Comment by danielfireman** [comment]
Irá ser corrigido em produção quando fechar #121
