### ISSUE TITLE
Corrigir parser do MPF

### ISSUE THREAD

**Issue by danielfireman** [dadosjusbr/coletores#182]
Três errinhos:

1. o [id da agência](https://github.com/dadosjusbr/coletores/blob/master/mpf/src/parser.py#L360) está em maiúsculo
2. está preenchendo o `procinfo` [aqui](https://github.com/dadosjusbr/coletores/blob/master/mpf/src/parser.py#L371) e não deveria
3. o [crawler version](https://github.com/dadosjusbr/coletores/blob/master/mpf/src/parser.py#L366) está preenchido errado, devemos pegar a variável de ambiente `GIT_COMMIT`

**Comment by danielfireman** [comment]
Seria bem bacana se o teste conseguisse pegar esses erros também

**Comment by joeberth** [comment]
Fui tentar rodar com o alba, encontrei um erro de typo, poderia verificar também, Thyago?
![image](https://user-images.githubusercontent.com/33490097/102345527-4c16f680-3f7c-11eb-8a43-6ddf82179b08.png)

Outro ponto importante é: Estamos adicionando a nossa saída, o gitCommit?

'RUN go build -ldflags "-X main.gitCommit=$GIT_COMMIT" -o main', em go utilizamos essa linha no Dockerfile.

**Comment by danielfireman** [comment]
> Outro ponto importante é: Estamos adicionando a nossa saída, o gitCommit?
> 
> 'RUN go build -ldflags "-X main.gitCommit=$GIT_COMMIT" -o main', em go utilizamos essa linha no Dockerfile.

Não consegui entender a pergunta, @joeberth

**Comment by joeberth** [comment]
Perdao, falha minha aí, editei.
