### ISSUE TITLE
Ajustes no MPM

### ISSUE THREAD

**Issue by joeberth** [dadosjusbr/coletores#189]
Ao tentar realizar o fluxo com docker, recebo algumas mensagens de erro.
-As primeiras estao relacionadas com a remoçao da libs que nao sao usadas no código.

Após essa etapa, recebo um erro de tipo no retorno:
![image](https://user-images.githubusercontent.com/33490097/102362678-70320200-3f93-11eb-9232-6770734aa321.png)

Estamos conseguindo rodar o fluxo completo do coletor com o docker?

**Comment by danielfireman** [comment]
@samarasss favor adicionar caso de teste que capture essa situação de erro.

**Comment by samarasss** [comment]
Não consegui reproduzir esse erro aqui. @joeberth  como tu tá passando as variáveis?

**Comment by danielfireman** [comment]
Esses erros já foram corrigidos e o MPM já está no site
