### ISSUE TITLE
Problema na coleta do MPM (Janeiro e novembro 2019)

### ISSUE THREAD

**Issue by samarasss** [dadosjusbr/coletores#260]
Problema no estágio de empacotamento. A seguinte mensagem aparece para os meses de Janeiro e novembro:
"stderr": "2021/03/03 16:29:56 \"error 5 , Error unmarshaling crawling resul from STDIN: \\\"invalid character 'N' looking for beginning of value\\\"\"\n",

**Comment by danielfireman** [comment]
@samarasss poderia colocar mais informações aqui? Por exemplo, um copiar e colar do resultado. Dessa forma a gente pode ter mais contexto e te ajudar.
