### ISSUE TITLE
Adicionar ao esquema a URL onde o pacote é armazenado

### ISSUE THREAD

**Issue by danielfireman** [dadosjusbr/coletores#50]
Precisaremos modificar o esquema de dados para ter a URL onde o pacote de dados se encontra

**Comment by davidedup** [comment]
@danielfireman, essa URL é a que esta no site do órgão ou seria uma URL onde nos salvamos esse dado?

**Comment by danielfireman** [comment]
A URL onde salvaremos o pacote de dados.

Utilizaremos o SWIFT para salvar esses pacotes de dados, da mesma forma que fazemos atualmente com os arquivos que fazemos download durante a coleta de dados.
